//
//  PGs.swift
//  TwoKBuilder
//
//  Created by Aleck David Holly on 2023-09-04.
//

import Foundation

let pointGuards: [PlayerRatings] = [
    PlayerRatings(name: "Lamelo Ball", height: "6'7", wingSpan: "6'10", weight: 180, image: .lamelo, finishing: Finishing(shotClose: 73, drivingLayup: 88, drivingDunk: 83, standingDunk: 45, postControl: 25), shooting: Shooting(midRange: 75, threePoint: 82, freeThrow: 84), playmaking: Playmaking(passing: 95, ballHandle: 87, speedWBall: 83), defense: Defense(interiorD: 25, perimD: 71, steal: 45, block: 44, offRebound: 25, defRebound: 60), physicals: Physicals(speed: 82, acceleration: 84, strength: 38, vertical: 70, stamina: 95)),
    PlayerRatings(name: "Jalen Brunson", height: "6'2", wingSpan: "6'4", weight: 190, image: .jalen, finishing: Finishing(shotClose: 96, drivingLayup: 90, drivingDunk: 45, standingDunk: 40, postControl: 25), shooting: Shooting(midRange: 94, threePoint: 85, freeThrow: 82), playmaking: Playmaking(passing: 87, ballHandle: 87, speedWBall: 83), defense: Defense(interiorD: 55, perimD: 60, steal: 45, block: 35, offRebound: 25, defRebound: 47), physicals: Physicals(speed: 82, acceleration: 82, strength: 40, vertical: 60, stamina: 95)),
    PlayerRatings(name: "Cade Cunningham", height: "6'7", wingSpan: "7'1", weight: 220, image: .cade, finishing: Finishing(shotClose: 81, drivingLayup: 85, drivingDunk: 73, standingDunk: 40, postControl: 60), shooting: Shooting(midRange: 90, threePoint: 80, freeThrow: 87), playmaking: Playmaking(passing: 80, ballHandle: 87, speedWBall: 81), defense: Defense(interiorD: 55, perimD: 75, steal: 45, block: 55, offRebound: 45, defRebound: 70), physicals: Physicals(speed: 81, acceleration: 78, strength: 55, vertical: 70, stamina: 99)),
    PlayerRatings(name: "Luka Doncic", height: "6'7", wingSpan: "6'8", weight: 230, image: .luka, finishing: Finishing(shotClose: 84, drivingLayup: 87, drivingDunk: 71, standingDunk: 45, postControl: 72), shooting: Shooting(midRange: 86, threePoint: 80, freeThrow: 75), playmaking: Playmaking(passing: 96, ballHandle: 85, speedWBall: 75), defense: Defense(interiorD: 44, perimD: 65, steal: 31, block: 40, offRebound: 40, defRebound: 66), physicals: Physicals(speed: 81, acceleration: 75, strength: 73, vertical: 60, stamina: 94)),
    PlayerRatings(name: "De'Aaron Fox", height: "6'3", wingSpan: "6'6", weight: 185, image: .fox, finishing: Finishing(shotClose: 84, drivingLayup: 91, drivingDunk: 75, standingDunk: 25, postControl: 25), shooting: Shooting(midRange: 83, threePoint: 77, freeThrow: 75), playmaking: Playmaking(passing: 80, ballHandle: 87, speedWBall: 90), defense: Defense(interiorD: 25, perimD: 71, steal: 40, block: 25, offRebound: 25, defRebound: 43), physicals: Physicals(speed: 90, acceleration: 91, strength: 44, vertical: 60, stamina: 99)),
    PlayerRatings(name: "Scoot Henderson", height: "6'2", wingSpan: "6'7", weight: 195, image: .scoot, finishing: Finishing(shotClose: 81, drivingLayup: 85, drivingDunk: 89, standingDunk: 25, postControl: 25), shooting: Shooting(midRange: 73, threePoint: 75, freeThrow: 78), playmaking: Playmaking(passing: 75, ballHandle: 85, speedWBall: 90), defense: Defense(interiorD: 25, perimD: 89, steal: 71, block: 31, offRebound: 34, defRebound: 45), physicals: Physicals(speed: 87, acceleration: 87, strength: 56, vertical: 85, stamina: 93)),
    PlayerRatings(name: "Jrue Holiday", height: "6'5", wingSpan: "6'7", weight: 205, image: .jrue, finishing: Finishing(shotClose: 81, drivingLayup: 80, drivingDunk: 60, standingDunk: 25, postControl: 25), shooting: Shooting(midRange: 82, threePoint: 80, freeThrow: 83), playmaking: Playmaking(passing: 80, ballHandle: 85, speedWBall: 75), defense: Defense(interiorD: 36, perimD: 95, steal: 83, block: 35, offRebound: 25, defRebound: 50), physicals: Physicals(speed: 80, acceleration: 79, strength: 45, vertical: 50, stamina: 99)),
    PlayerRatings(name: "Kyrie Irving", height: "6'2", wingSpan: "6'4", weight: 195, image: .kyrieIrving, finishing: Finishing(shotClose: 82, drivingLayup: 91, drivingDunk: 30, standingDunk: 25, postControl: 64), shooting: Shooting(midRange: 91, threePoint: 82, freeThrow: 83), playmaking: Playmaking(passing: 87, ballHandle: 98, speedWBall: 83), defense: Defense(interiorD: 34, perimD: 58, steal: 25, block: 36, offRebound: 35, defRebound: 45), physicals: Physicals(speed: 82, acceleration: 87, strength: 41, vertical: 57, stamina: 99)),
    PlayerRatings(name: "Russell Westbrook", height: "6'3", wingSpan: "6'7", weight: 200, image: .westbrook, finishing: Finishing(shotClose: 77, drivingLayup: 82, drivingDunk: 83, standingDunk: 25, postControl: 60), shooting: Shooting(midRange: 72, threePoint: 70, freeThrow: 65), playmaking: Playmaking(passing: 77, ballHandle: 87, speedWBall: 89), defense: Defense(interiorD: 40, perimD: 75, steal: 60, block: 40, offRebound: 40, defRebound: 62), physicals: Physicals(speed: 89, acceleration: 89, strength: 68, vertical: 80, stamina: 93)),
    PlayerRatings(name: "Trae Young", height: "6'1", wingSpan: "6'3", weight: 164, image: .trae, finishing: Finishing(shotClose: 92, drivingLayup: 91, drivingDunk: 25, standingDunk: 25, postControl: 25), shooting: Shooting(midRange: 82, threePoint: 85, freeThrow: 90), playmaking: Playmaking(passing: 83, ballHandle: 95, speedWBall: 87), defense: Defense(interiorD: 25, perimD: 60, steal: 45, block: 45, offRebound: 38, defRebound: 50), physicals: Physicals(speed: 84, acceleration: 87, strength: 47, vertical: 65, stamina: 96))
]

let shootingGuards: [PlayerRatings] = [
    PlayerRatings(name: "Bradley Beal", height: "6'4", wingSpan: "6'8", weight: 207, image: .beal, finishing: Finishing(shotClose: 87, drivingLayup: 91, drivingDunk: 81, standingDunk: 25, postControl: 60), shooting: Shooting(midRange: 90, threePoint: 80, freeThrow: 85), playmaking: Playmaking(passing: 77, ballHandle: 87, speedWBall: 75), defense: Defense(interiorD: 28, perimD: 60, steal: 45, block: 53, offRebound: 25, defRebound: 40), physicals: Physicals(speed: 75, acceleration: 83, strength: 60, vertical: 70, stamina: 99)),
    PlayerRatings(name: "Jaylen Brown", height: "6'6", wingSpan: "6'11", weight: 223, image: .jaybrown, finishing: Finishing(shotClose: 81, drivingLayup: 87, drivingDunk: 86, standingDunk: 40, postControl: 72), shooting: Shooting(midRange: 89, threePoint: 80, freeThrow: 75), playmaking: Playmaking(passing: 75, ballHandle: 80, speedWBall: 75), defense: Defense(interiorD: 55, perimD: 85, steal: 71, block: 30, offRebound: 35, defRebound: 60), physicals: Physicals(speed: 75, acceleration: 75, strength: 53, vertical: 75, stamina: 93)),
    PlayerRatings(name: "Anthony Edwards", height: "6'4", wingSpan: "6'9", weight: 225, image: .anthonyedwards, finishing: Finishing(shotClose: 75, drivingLayup: 85, drivingDunk: 90, standingDunk: 40, postControl: 60), shooting: Shooting(midRange: 76, threePoint: 80, freeThrow: 80), playmaking: Playmaking(passing: 75, ballHandle: 85, speedWBall: 80), defense: Defense(interiorD: 26, perimD: 71, steal: 60, block: 35, offRebound: 26, defRebound: 62), physicals: Physicals(speed: 82, acceleration: 80, strength: 51, vertical: 82, stamina: 93)),
    PlayerRatings(name: "Josh Giddey", height: "6'8", wingSpan: "7'0", weight: 216, image: .giddey, finishing: Finishing(shotClose: 90, drivingLayup: 91, drivingDunk: 65, standingDunk: 45, postControl: 60), shooting: Shooting(midRange: 76, threePoint: 75, freeThrow: 77), playmaking: Playmaking(passing: 95, ballHandle: 85, speedWBall: 77), defense: Defense(interiorD: 60, perimD: 71, steal: 40, block: 51, offRebound: 55, defRebound: 75), physicals: Physicals(speed: 80, acceleration: 74, strength: 60, vertical: 75, stamina: 93)),
    PlayerRatings(name: "Tyler Herro", height: "6'5", wingSpan: "6'5", weight: 195, image: .herro, finishing: Finishing(shotClose: 95, drivingLayup: 88, drivingDunk: 60, standingDunk: 35, postControl: 44), shooting: Shooting(midRange: 80, threePoint: 87, freeThrow: 96), playmaking: Playmaking(passing: 79, ballHandle: 85, speedWBall: 75), defense: Defense(interiorD: 46, perimD: 73, steal: 40, block: 42, offRebound: 31, defRebound: 64), physicals: Physicals(speed: 80, acceleration: 80, strength: 60, vertical: 72, stamina: 93)),
    PlayerRatings(name: "Zach Lavine", height: "6'5", wingSpan: "6'8", weight: 200, image: .zach, finishing: Finishing(shotClose: 81, drivingLayup: 85, drivingDunk: 90, standingDunk: 50, postControl: 60), shooting: Shooting(midRange: 80, threePoint: 80, freeThrow: 80), playmaking: Playmaking(passing: 77, ballHandle: 84, speedWBall: 80), defense: Defense(interiorD: 50, perimD: 64, steal: 30, block: 31, offRebound: 29, defRebound: 45), physicals: Physicals(speed: 81, acceleration: 80, strength: 45, vertical: 85, stamina: 97)),
    PlayerRatings(name: "Austin Reaves", height: "6'5", wingSpan: "6'6", weight: 197, image: .reaves, finishing: Finishing(shotClose: 94, drivingLayup: 82, drivingDunk: 73, standingDunk: 25, postControl: 33), shooting: Shooting(midRange: 93, threePoint: 85, freeThrow: 86), playmaking: Playmaking(passing: 70, ballHandle: 76, speedWBall: 75), defense: Defense(interiorD: 35, perimD: 75, steal: 40, block: 35, offRebound: 43, defRebound: 50), physicals: Physicals(speed: 83, acceleration: 84, strength: 46, vertical: 75, stamina: 95)),
    PlayerRatings(name: "Marcus Smart", height: "6'4", wingSpan: "6'8", weight: 220, image: .marcussmart, finishing: Finishing(shotClose: 86, drivingLayup: 76, drivingDunk: 50, standingDunk: 25, postControl: 61), shooting: Shooting(midRange: 69, threePoint: 82, freeThrow: 77), playmaking: Playmaking(passing: 77, ballHandle: 76, speedWBall: 75), defense: Defense(interiorD: 70, perimD: 95, steal: 83, block: 50, offRebound: 26, defRebound: 51), physicals: Physicals(speed: 80, acceleration: 83, strength: 75, vertical: 72, stamina: 95)),
    PlayerRatings(name: "Klay Thompson", height: "6'8", wingSpan: "6'8", weight: 110, image: .klay, finishing: Finishing(shotClose: 91, drivingLayup: 75, drivingDunk: 70, standingDunk: 25, postControl: 25), shooting: Shooting(midRange: 90, threePoint: 92, freeThrow: 85), playmaking: Playmaking(passing: 77, ballHandle: 76, speedWBall: 75), defense: Defense(interiorD: 71, perimD: 84, steal: 50, block: 51, offRebound: 25, defRebound: 60), physicals: Physicals(speed: 75, acceleration: 75, strength: 63, vertical: 67, stamina: 93)),
]

let smallForwards: [PlayerRatings] = [
    PlayerRatings(name: "Mikal Bridges", height: "6'6", wingSpan: "7'2", weight: 209, image: .mikal, finishing: Finishing(shotClose: 86, drivingLayup: 74, drivingDunk: 71, standingDunk: 45, postControl: 55), shooting: Shooting(midRange: 86, threePoint: 84, freeThrow: 85), playmaking: Playmaking(passing: 75, ballHandle: 80, speedWBall: 75), defense: Defense(interiorD: 45, perimD: 89, steal: 83, block: 45, offRebound: 30, defRebound: 60), physicals: Physicals(speed: 78, acceleration: 78, strength: 57, vertical: 70, stamina: 93)),
    PlayerRatings(name: "Jimmy Butler", height: "6'7", wingSpan: "6'8", weight: 230, image: .butler, finishing: Finishing(shotClose: 84, drivingLayup: 85, drivingDunk: 80, standingDunk: 40, postControl: 81), shooting: Shooting(midRange: 76, threePoint: 79, freeThrow: 81), playmaking: Playmaking(passing: 80, ballHandle: 80, speedWBall: 75), defense: Defense(interiorD: 58, perimD: 87, steal: 89, block: 25, offRebound: 60, defRebound: 45), physicals: Physicals(speed: 80, acceleration: 75, strength: 67, vertical: 60, stamina: 99)),
    PlayerRatings(name: "Paul George", height: "6'8", wingSpan: "6'11", weight: 220, image: .paulg, finishing: Finishing(shotClose: 81, drivingLayup: 85, drivingDunk: 85, standingDunk: 50, postControl: 65), shooting: Shooting(midRange: 80, threePoint: 80, freeThrow: 85), playmaking: Playmaking(passing: 76, ballHandle: 85, speedWBall: 75), defense: Defense(interiorD: 60, perimD: 91, steal: 70, block: 40, offRebound: 25, defRebound: 60), physicals: Physicals(speed: 79, acceleration: 74, strength: 65, vertical: 75, stamina: 93)),
    PlayerRatings(name: "Brandon Ingram", height: "6'8", wingSpan: "7'3", weight: 190, image: .brandoni, finishing: Finishing(shotClose: 85, drivingLayup: 90, drivingDunk: 80, standingDunk: 65, postControl: 72), shooting: Shooting(midRange: 89, threePoint: 81, freeThrow: 86), playmaking: Playmaking(passing: 75, ballHandle: 85, speedWBall: 75), defense: Defense(interiorD: 60, perimD: 71, steal: 40, block: 51, offRebound: 40, defRebound: 60), physicals: Physicals(speed: 75, acceleration: 75, strength: 73, vertical: 62, stamina: 95)),
    PlayerRatings(name: "Michael Porter Jr.", height: "6'10", wingSpan: "7'0", weight: 218, image: .mpjr, finishing: Finishing(shotClose: 90, drivingLayup: 88, drivingDunk: 83, standingDunk: 60, postControl: 67), shooting: Shooting(midRange: 91, threePoint: 84, freeThrow: 80), playmaking: Playmaking(passing: 75, ballHandle: 76, speedWBall: 69), defense: Defense(interiorD: 70, perimD: 71, steal: 50, block: 55, offRebound: 50, defRebound: 70), physicals: Physicals(speed: 76, acceleration: 68, strength: 73, vertical: 85, stamina: 95)),
    PlayerRatings(name: "Jayson Tatum", height: "6'8", wingSpan: "6'10", weight: 210, image: .jayson, finishing: Finishing(shotClose: 77, drivingLayup: 84, drivingDunk: 83, standingDunk: 45, postControl: 81), shooting: Shooting(midRange: 82, threePoint: 82, freeThrow: 81), playmaking: Playmaking(passing: 75, ballHandle: 80, speedWBall: 75), defense: Defense(interiorD: 65, perimD: 85, steal: 65, block: 68, offRebound: 40, defRebound: 70), physicals: Physicals(speed: 75, acceleration: 75, strength: 60, vertical: 74, stamina: 93)),
]

let powerForwards: [PlayerRatings] = [
    PlayerRatings(name: "Paulo Banchero", height: "6'10", wingSpan: "7'0", weight: 250, image: .paulo, finishing: Finishing(shotClose: 85, drivingLayup: 88, drivingDunk: 87, standingDunk: 76, postControl: 73), shooting: Shooting(midRange: 80, threePoint: 76, freeThrow: 77), playmaking: Playmaking(passing: 75, ballHandle: 76, speedWBall: 65), defense: Defense(interiorD: 70, perimD: 71, steal: 40, block: 60, offRebound: 60, defRebound: 79), physicals: Physicals(speed: 71, acceleration: 62, strength: 84, vertical: 87, stamina: 96)),
    PlayerRatings(name: "Aaron Gordon", height: "6'8", wingSpan: "6'11", weight: 235, image: .aarongordon, finishing: Finishing(shotClose: 81, drivingLayup: 80, drivingDunk: 95, standingDunk: 90, postControl: 72), shooting: Shooting(midRange: 65, threePoint: 80, freeThrow: 65), playmaking: Playmaking(passing: 68, ballHandle: 60, speedWBall: 65), defense: Defense(interiorD: 70, perimD: 75, steal: 40, block: 68, offRebound: 87, defRebound: 65), physicals: Physicals(speed: 68, acceleration: 67, strength: 70, vertical: 87, stamina: 93)),
    PlayerRatings(name: "Draymond Green", height: "6'6", wingSpan: "7'1", weight: 230, image: .draymond, finishing: Finishing(shotClose: 95, drivingLayup: 72, drivingDunk: 65, standingDunk: 55, postControl: 68), shooting: Shooting(midRange: 72, threePoint: 75, freeThrow: 75), playmaking: Playmaking(passing: 90, ballHandle: 75, speedWBall: 75), defense: Defense(interiorD: 87, perimD: 87, steal: 51, block: 70, offRebound: 50, defRebound: 80), physicals: Physicals(speed: 73, acceleration: 75, strength: 73, vertical: 70, stamina: 95)),
    PlayerRatings(name: "Jaren Jackson Jr.", height: "6'10", wingSpan: "7'4", weight: 242, image: .jarenjackson, finishing: Finishing(shotClose: 90, drivingLayup: 76, drivingDunk: 80, standingDunk: 81, postControl: 74), shooting: Shooting(midRange: 87, threePoint: 80, freeThrow: 79), playmaking: Playmaking(passing: 60, ballHandle: 55, speedWBall: 26), defense: Defense(interiorD: 90, perimD: 71, steal: 40, block: 93, offRebound: 57, defRebound: 70), physicals: Physicals(speed: 63, acceleration: 63, strength: 70, vertical: 75, stamina: 93)),
    PlayerRatings(name: "Cameron Johnson", height: "6'8", wingSpan: "6'10", weight: 210, image: .cameron, finishing: Finishing(shotClose: 91, drivingLayup: 80, drivingDunk: 70, standingDunk: 70, postControl: 73), shooting: Shooting(midRange: 94, threePoint: 86, freeThrow: 85), playmaking: Playmaking(passing: 68, ballHandle: 68, speedWBall: 45), defense: Defense(interiorD: 75, perimD: 75, steal: 65, block: 55, offRebound: 50, defRebound: 70), physicals: Physicals(speed: 75, acceleration: 73, strength: 65, vertical: 80, stamina: 93)),
    PlayerRatings(name: "Lauri Markkanen", height: "7'0", wingSpan: "7'0", weight: 240, image: .markkanen, finishing: Finishing(shotClose: 98, drivingLayup: 82, drivingDunk: 75, standingDunk: 80, postControl: 84), shooting: Shooting(midRange: 88, threePoint: 82, freeThrow: 92), playmaking: Playmaking(passing: 70, ballHandle: 67, speedWBall: 50), defense: Defense(interiorD: 70, perimD: 66, steal: 45, block: 61, offRebound: 65, defRebound: 85), physicals: Physicals(speed: 68, acceleration: 60, strength: 70, vertical: 70, stamina: 96)),
    PlayerRatings(name: "Evan Mobley", height: "6'11", wingSpan: "7'4", weight: 215, image: .mobley, finishing: Finishing(shotClose: 81, drivingLayup: 82, drivingDunk: 80, standingDunk: 85, postControl: 81), shooting: Shooting(midRange: 78, threePoint: 70, freeThrow: 71), playmaking: Playmaking(passing: 70, ballHandle: 60, speedWBall: 65), defense: Defense(interiorD: 85, perimD: 70, steal: 40, block: 87, offRebound: 70, defRebound: 82), physicals: Physicals(speed: 68, acceleration: 67, strength: 62, vertical: 70, stamina: 94)),
    PlayerRatings(name: "Pascal Siakam", height: "6'8", wingSpan: "7'3", weight: 230, image: .siakam, finishing: Finishing(shotClose: 90, drivingLayup: 84, drivingDunk: 80, standingDunk: 81, postControl: 85), shooting: Shooting(midRange: 80, threePoint: 76, freeThrow: 77), playmaking: Playmaking(passing: 75, ballHandle: 80, speedWBall: 75), defense: Defense(interiorD: 75, perimD: 76, steal: 40, block: 47, offRebound: 42, defRebound: 75), physicals: Physicals(speed: 72, acceleration: 72, strength: 70, vertical: 67, stamina: 95)),
    PlayerRatings(name: "Karl-Anthony Towns", height: "7'0", wingSpan: "7'3", weight: 248, image: .karltowns, finishing: Finishing(shotClose: 94, drivingLayup: 80, drivingDunk: 75, standingDunk: 90, postControl: 86), shooting: Shooting(midRange: 90, threePoint: 80, freeThrow: 85), playmaking: Playmaking(passing: 53, ballHandle: 67, speedWBall: 58), defense: Defense(interiorD: 75, perimD: 55, steal: 45, block: 55, offRebound: 60, defRebound: 86), physicals: Physicals(speed: 67, acceleration: 57, strength: 86, vertical: 75, stamina: 97)),
]

let centers: [PlayerRatings] = [
    PlayerRatings(name: "Deandre Ayton", height: "7'0", wingSpan: "7'4", weight: 250, image: .deandre, finishing: Finishing(shotClose: 95, drivingLayup: 70, drivingDunk: 75, standingDunk: 90, postControl: 81), shooting: Shooting(midRange: 82, threePoint: 70, freeThrow: 77), playmaking: Playmaking(passing: 60, ballHandle: 60, speedWBall: 55), defense: Defense(interiorD: 80, perimD: 50, steal: 25, block: 70, offRebound: 70, defRebound: 86), physicals: Physicals(speed: 66, acceleration: 56, strength: 86, vertical: 80, stamina: 94)),
    PlayerRatings(name: "Anthony Davis", height: "6'10", wingSpan: "7'6", weight: 252, image: .davis, finishing: Finishing(shotClose: 90, drivingLayup: 70, drivingDunk: 82, standingDunk: 81, postControl: 81), shooting: Shooting(midRange: 76, threePoint: 70, freeThrow: 78), playmaking: Playmaking(passing: 60, ballHandle: 70, speedWBall: 55), defense: Defense(interiorD: 85, perimD: 71, steal: 36, block: 87, offRebound: 70, defRebound: 86), physicals: Physicals(speed: 65, acceleration: 60, strength: 70, vertical: 70, stamina: 92)),
    PlayerRatings(name: "Andre Drummond", height: "6'11", wingSpan: "7'6", weight: 279, image: .drummond, finishing: Finishing(shotClose: 85, drivingLayup: 70, drivingDunk: 80, standingDunk: 92, postControl: 72), shooting: Shooting(midRange: 46, threePoint: 25, freeThrow: 60), playmaking: Playmaking(passing: 68, ballHandle: 33, speedWBall: 34), defense: Defense(interiorD: 80, perimD: 35, steal: 65, block: 68, offRebound: 900, defRebound: 95), physicals: Physicals(speed: 63, acceleration: 51, strength: 90, vertical: 75, stamina: 95)),
    PlayerRatings(name: "Nikola Jokic", height: "6'11", wingSpan: "7'3", weight: 284, image: .jokic, finishing: Finishing(shotClose: 95, drivingLayup: 80, drivingDunk: 70, standingDunk: 83, postControl: 90), shooting: Shooting(midRange: 89, threePoint: 80, freeThrow: 82), playmaking: Playmaking(passing: 92, ballHandle: 61, speedWBall: 50), defense: Defense(interiorD: 70, perimD: 50, steal: 41, block: 48, offRebound: 60, defRebound: 86), physicals: Physicals(speed: 60, acceleration: 50, strength: 86, vertical: 63, stamina: 94)),
    PlayerRatings(name: "Domantas Sabonis", height: "7'1", wingSpan: "7'1", weight: 240, image: .sabonis, finishing: Finishing(shotClose: 98, drivingLayup: 84, drivingDunk: 75, standingDunk: 70, postControl: 90), shooting: Shooting(midRange: 90, threePoint: 82, freeThrow: 76), playmaking: Playmaking(passing: 83, ballHandle: 65, speedWBall: 45), defense: Defense(interiorD: 70, perimD: 50, steal: 36, block: 51, offRebound: 75, defRebound: 90), physicals: Physicals(speed: 50, acceleration: 45, strength: 86, vertical: 59, stamina: 95)),
    PlayerRatings(name: "Myles Turner", height: "6'11", wingSpan: "7'4", weight: 250, image: .mylesturner, finishing: Finishing(shotClose: 94, drivingLayup: 80, drivingDunk: 65, standingDunk: 81, postControl: 81), shooting: Shooting(midRange: 82, threePoint: 81, freeThrow: 79), playmaking: Playmaking(passing: 60, ballHandle: 35, speedWBall: 25), defense: Defense(interiorD: 90, perimD: 71, steal: 35, block: 92, offRebound: 55, defRebound: 86), physicals: Physicals(speed: 52, acceleration: 52, strength: 77, vertical: 75, stamina: 95)),
]
